project_name: inc
env:
- GO111MODULE=on
before:
  hooks:
  - go mod tidy
builds:
- main: github.com/brimstone/inc/cmd/inc-client
  binary: inc-client
  ldflags:
  - -s -w
  - -X main.Version={{.Version}}
  - -X main.Revision={{.ShortCommit}}
  env:
  - CGO_ENABLED=0
  goarm:
  - "6"
  goarch:
  - amd64
  - arm
archives:
- name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  replacements:
    darwin: darwin
    linux: linux
    windows: windows
    386: i386
    amd64: x86_64
  format_overrides:
  - goos: windows
    format: zip
release:
  prerelease: auto
